#!/bin/bash

# fetch_lyrics () {
# 	song=`curl -s --get "https://makeitpersonal.co/lyrics" --data-urlencode "artist=$artist" --data-urlencode "title=$title"`;
# }

# artist=$1
# title=$2
# fetch_lyrics
# if [ "$song" == "Sorry, We don't have lyrics for this song yet." ]; then
# 	title=$1
# 	artist=$2
# 	fetch_lyrics
# fi

# echo -e "$artist - $title\n$song"


# -----------------------------------------------------------------------------------------------------------



# curl 'https://www.lyrics007.com/search.php?category=artist&q=michael+buble'

PROGNAME=$0
SITE_URL="https://www.lyrics007.com"

invalid() {
  if [ -z "$error" -a "$error"!=" " ]; then
    error="Invalid command."
  fi

  cat << EOF >&2
$error 
Try '$PROGNAME --help' for more information.
EOF
  exit 1
}

usage() {
  cat << EOF >&2
Usage: $PROGNAME [OPTIONS] [TEXT]

Options (default value in (), *required):
  -c, --clip                    List song by matching lyrics clip
  -a, --artist                  List song by Artist's Name
  -t, --title                   List song by matching title
      --help                    display this help and exit
EOF
  exit 1
}

whiteSpaceCleaner() {
  # removes extra white space
  text="$(echo "$text" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

textChanger() {
  whiteSpaceCleaner
  # converts internal space to underscore for display
  text="$(echo "$text" | sed -e 's/\ /_/g')"
}

sanitizeText() {
  whiteSpaceCleaner
  # converts to lowercase
  text="$(echo "$text" | sed -e 's/\(.*\)/\L\1/g')"
  # converts internal space to plus for web search
  text="$(echo "$text" | sed -e 's/\ /+/g')"
}

checkEmptyTextAndClean() {
  if [ -z "$text" -a "$text"!=" " ]; then
    error="Invalid command, requires text to search."
    invalid
    exit 1
  else
    sanitizeText
  fi
}

lyricsDisplay() {
  lyricsLink=${URLS[$REPLY]}
  lyrics=`curl -s --get "$SITE_URL$lyricsLink" | sed -n "/<div class=\"lyrics\">/,/<\/div>/p"| sed -e 's/<br>/\\\n/g' -e 's/<BR>/\\\n/g' | sed -e 's/<[^>]*>//g'`;
  echo -en " "$lyrics
  exit 1
}

fetchSongs() {
  song=`curl -s --get "$SITE_URL/search.php?$string" | grep "scroll" | sed -n 's/.*href="\([^"]*\).*/\1/p'`;
  actionList=`curl -s --get "$SITE_URL$song" | sed -n "/<ul class=\"song_title\">/,/<\/ul>/p" | sed "s/<a href/\\n<a href/g" | grep "a href"`
  list=`sed -e 's/<\/a>/ /g' -e 's/[<|>]//g' -e 's/a href=\"//g' -e 's/"/ /g' <<< $actionList`;
  # urls=`sed -e 's/.*href="\([^"]*\).*/\1/p' <<< $list`;
  # titles=`sed -e 's/<[^>]*>//g' <<< $list`;

  count=1
  while IFS=" " read -r url text
  do 
    textChanger    
    TITLES[`expr $count`]=$text
    URLS[`expr $count`]=$url
    # echo $text
    count=`expr $count + 1`
  done <<< "$list"

  # echo $count
  # echo ${TITLES[100]}
  # echo ${URLS[100]}

  select key in ${TITLES[@]}; do
    echo "You picked ${REPLY}. Displaying lyrics of ${key}"
    echo "============================================================="
    lyricsDisplay
  done
}

searchFromClip() {
  checkEmptyTextAndClean
  cat << EOF >&2
The clip is $text
EOF
  exit 1
}

searchFromArtist() {
  checkEmptyTextAndClean
  string="category=artist&q=$text"
  fetchSongs
  exit 1
}

searchFromTitle() {
  checkEmptyTextAndClean
  cat << EOF >&2
The title is $text
EOF
  exit 1
}

while true; do
  case $1 in
    (-c|--clip) shift; text=$@; searchFromClip;;
    (-a|--artist) shift; text=$@; searchFromArtist;;
    (-t|--title) shift; text=$@; searchFromTitle;;
    (--help) usage;;
    (*) invalid
  esac
done