#!/bin/bash

PROGNAME=$0
SITE_URL="https://www.lyrics007.com"

invalid() {
  if [ -z "$error" -a "$error"!=" " ]; then
    error="Invalid command."
  fi

  cat << EOF >&2
$error 
Try '$PROGNAME --help' for more information.
EOF
  exit 1
}

usage() {
  cat << EOF >&2
Usage: $PROGNAME [OPTIONS] [TEXT]

Options:
  -s, --song                    List song by matching song title
  -a, --artist                  List song by Artist's name
  -b, --both                    List song by matching both song and artist, separated by dash(-), any order.
      --help                    display this help and exit
EOF
  exit 1
}

whiteSpaceCleaner() {
  # removes extra white space
  text="$(echo "$text" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

textChanger() {
  whiteSpaceCleaner
  # converts internal space to underscore for display
  text="$(echo "$text" | sed -e 's/\ /_/g')"
  # this is the case for search by song title
  if echo "$text" | grep -q "_-_"; then
    text="$(echo -en "$text" | sed -e 's/_-_/(/g' | sed -e 's/$/)/g')"
  fi
}

sanitizeText() {
  whiteSpaceCleaner
  if echo "$text" | grep -q " - "; then
    title="$(echo "$text" | cut -d"-" -f1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    artist="$(echo "$text" | cut -d"-" -f2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  else
    # converts to lowercase
    text="$(echo "$text" | sed -e 's/\(.*\)/\L\1/g')"
    # converts internal space to plus for web search
    text="$(echo "$text" | sed -e 's/\ /+/g')"
  fi
}

checkEmptyTextAndClean() {
  if [ -z "$text" -a "$text"!=" " ]; then
    error="Invalid command, requires text to search."
    invalid
    exit 1
  else
    sanitizeText
  fi
}

lyricsDisplay() {
  lyricsLink=${URLS[$REPLY]}
  lyrics=`curl -s --get "$SITE_URL$lyricsLink" | sed -n "/<div class=\"lyrics\">/,/<\/div>/p"| sed -e 's/<br>/\\\n/g' -e 's/<BR>/\\\n/g' | sed -e 's/<[^>]*>//g'`;
  echo -en " "$lyrics
  exit 1
}

fetchSongsFromList() {
  count=1
  while IFS=" " read -r url text
  do 
    textChanger    
    TITLES[`expr $count`]=$text
    URLS[`expr $count`]=$url
    # echo $text
    count=`expr $count + 1`
  done <<< "$list"

  # echo $count
  # echo ${TITLES[100]}
  # echo ${URLS[100]}

  select key in ${TITLES[@]}; do
    echo "You picked ${REPLY}. Displaying lyrics of ${key}"
    echo "============================================================="
    lyricsDisplay
  done
}

fetchSongsFromArtist() {
  song=`curl -s --get "$SITE_URL/search.php?$string" | grep "scroll" | sed -n 's/.*href="\([^"]*\).*/\1/p'`;
  actionList=`curl -s --get "$SITE_URL$song" | sed -n "/<ul class=\"song_title\">/,/<\/ul>/p" | sed "s/<a href/\\n<a href/g" | grep "a href"`
  list=`sed -e 's/<\/a>/ /g' -e 's/[<|>]//g' -e 's/a href=\"//g' -e 's/"/ /g' <<< $actionList`;
  # urls=`sed -e 's/.*href="\([^"]*\).*/\1/p' <<< $list`;
  # titles=`sed -e 's/<[^>]*>//g' <<< $list`;
  fetchSongsFromList
}

fetchSongsFromSongTitle() {
  echo "$SITE_URL/search.php?$string"
  # song=`curl -s --get "$SITE_URL/search.php?$string" | grep "scroll" | sed -n 's/.*href="\([^"]*\).*/\1/p'`;
  text=`curl -s --get "https://www.lyrics007.com/search.php?category=song&q=best+of+me" | sed -n "/<div class=\"scroll\">/,/<\/div>/p" | sed -e 's/<div[^>]*>//g' | sed -e 's/<h2[^>]*>//g' -e 's/<\/h2[^>]*>/ - /g'`;
  whiteSpaceCleaner
  actionList=`sed -e 's/<a href=\"/\\\n/g' -e 's/">/ /g' -e 's/<\/a>//g' -e 's/<\/div>//g' <<< $text`;
  list=`echo -en $actionList`

  fetchSongsFromList
}

fetchSongsFromBothTitleAndArtist () {
	song=`curl -s --get "https://makeitpersonal.co/lyrics" --data-urlencode "artist=$artist" --data-urlencode "title=$title"`;
}

searchFromTitle() {
  checkEmptyTextAndClean
  string="category=song&q=$text"
  fetchSongsFromSongTitle
  exit 1
}

searchFromArtist() {
  checkEmptyTextAndClean
  string="category=artist&q=$text"
  fetchSongsFromArtist
  exit 1
}

searchFromBothTitleAndArtist() {
  if echo "$text" | grep -q " - "; then
    checkEmptyTextAndClean
    fetchSongsFromBothTitleAndArtist

    if [ "$song" == "Sorry, We don't have lyrics for this song yet." ]; then
      oldtitle=$artist
      artist=$title
      title=$oldtitle

      fetchSongsFromBothTitleAndArtist
    fi

    if [ "$song" == "Sorry, We don't have lyrics for this song yet." ]; then
      error="Sorry, We can't find the lyrics directly. You can search the lyrics by artist name or song title."
      invalid
    else
      echo -en "$song"
    fi
  else
    error="Invalid command, requires dash separated artist - title, or, title - artist. Example: $PROGNAME -b Frank Sinatra - New York"
    invalid
  fi
  exit 1
}

while true; do
  case $1 in
    (-s|--song) shift; text=$@; searchFromTitle;;
    (-a|--artist) shift; text=$@; searchFromArtist;;
    (-b|--both) shift; text=$@; searchFromBothTitleAndArtist;;
    (--help) usage;;
    (*) invalid
  esac
done